server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/it592api?useSSL=false
spring.datasource.username=root
spring.datasource.password=9839
spring.jpa.hibernate.ddl-auto=update
spring.data.jpa.repositories.enabled=true
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true